import os
import json
import asyncio
import google.generativeai as genai

class ReviewerAgent:
    """
    Acts as a critical analyst for historical narratives generated by the NarrativeAgent.
    Checks for historical accuracy, demographic relevance, and engagement.
    """
    async def execute(self, state):
        context = state.get("context")
        draft = state.get("story")
        
        # If there's no story yet, pass
        if not draft:
            return state
            
        review_result = await self.run(context, draft)
        state.set("review", review_result)
        return state

    async def run(self, context, draft):
        place = context.get("place", "Unknown")
        era = context.get("context", "Unknown")
        age = context.get("age")
        origin = context.get("origin")
        background = context.get("background")
        language = context.get("language", "English")

        prompt = (
            f"You are an expert Historical Editor and AI Output Critic. "
            f"Your job is to critically analyze a generated historical narrative about '{place}' during the '{era}'.\n\n"
            f"Here is the user profile the narrative was supposed to be tailored for:\n"
            f"- Age: {age or 'Any'}\n"
            f"- Origin: {origin or 'Any'}\n"
            f"- Background/Profession: {background or 'Any'}\n"
            f"- Language: {language}\n\n"
            f"Here is the generated draft:\n"
            f"\"\"\"\n{draft.get('story', '')}\n\"\"\"\n\n"
            f"Analyze the draft based on these criteria:\n"
            f"1. Accuracy & Hallucination: Does it invent fake history?\n"
            f"2. Relevance: Does it successfully integrate the user's Age, Origin, and Background (e.g. analogies) without being too forced?\n"
            f"3. Quality: Is the tone engaging and educational?\n\n"
            f"Provide your output as a strict JSON object with EXACTLY these three keys:\n"
            f"  \"pass\": true or false (true if score is 8 or higher)\n"
            f"  \"score\": integer from 1 to 10\n"
            f"  \"feedback\": string containing specific instructions for the writer on how to fix it (if pass is false)\n"
        )

        try:
            api_key = os.getenv("GOOGLE_API_KEY")
            if api_key:
                genai.configure(api_key=api_key, transport='rest')
                
            model = genai.GenerativeModel("gemini-3.5-flash", generation_config={"response_mime_type": "application/json"})
            
            creds = os.environ.pop("GOOGLE_APPLICATION_CREDENTIALS", None)
            
            try:
                loop = asyncio.get_running_loop()
                response = await loop.run_in_executor(None, lambda: model.generate_content(prompt))
                result_text = response.text.strip()
                if result_text.startswith("```json"):
                    result_text = result_text[7:]
                if result_text.endswith("```"):
                    result_text = result_text[:-3]
                result_text = result_text.strip()
                result = json.loads(result_text)
            finally:
                if creds is not None:
                    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = creds
                    
            return {
                "is_pass": result.get("pass", True),
                "score": result.get("score", 10),
                "feedback": result.get("feedback", ""),
            }

        except Exception as e:
            print(f"ReviewerAgent failed: {e}")
            # Failsafe: if the critic fails, just pass it through so the user still gets a story
            return {
                "is_pass": True,
                "score": 10,
                "feedback": "Critic offline. Approved by default."
            }
